#conda activate Ada-gat
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.6 --attr_drop=0.6 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.5 --attr_drop=0.6 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.6 --attr_drop=0.5 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.5 --attr_drop=0.5 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.4 --attr_drop=0.5 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.5 --attr_drop=0.4 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.4 --attr_drop=0.4 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.4 --attr_drop=0.3 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.3 --attr_drop=0.4 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.3 --attr_drop=0.3 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.3 --attr_drop=0.2 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.2 --attr_drop=0.3 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.2 --attr_drop=0.2 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.2 --attr_drop=0.1 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.1 --attr_drop=0.2 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.1 --attr_drop=0.1 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0 --attr_drop=0.1 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0.1 --attr_drop=0 --dataset=citeseer --self_loop=True
python main.py  --lr=0.01 --weight_decay=0.0005 --filterbanks='ALL' --feat_drop=0 --attr_drop=0 --dataset=citeseer --self_loop=True