#conda activate Ada-gat
python main.py  --hidden=2048 
python main.py  --hidden=1024  
python main.py  --hidden=512 
python main.py  --hidden=256 
python main.py  --hidden=128 
python main.py  --hidden=64 
python main.py  --hidden=32 
python main.py  --hidden=8 
