#conda activate Ada-gat
python main.py  --feat_drop=0 --attr_drop=0.6
python main.py  --feat_drop=0 --attr_drop=0.5
python main.py  --feat_drop=0 --attr_drop=0.4
python main.py  --feat_drop=0 --attr_drop=0.3
python main.py  --feat_drop=0 --attr_drop=0.2
python main.py  --feat_drop=0 --attr_drop=0.1
python main.py  --feat_drop=0 --attr_drop=0
python main.py  --feat_drop=0.1 --attr_drop=0.6
python main.py  --feat_drop=0.1 --attr_drop=0.5
python main.py  --feat_drop=0.1 --attr_drop=0.4
python main.py  --feat_drop=0.1 --attr_drop=0.3
python main.py  --feat_drop=0.1 --attr_drop=0.2
python main.py  --feat_drop=0.1 --attr_drop=0.1
python main.py  --feat_drop=0.1 --attr_drop=0
python main.py  --feat_drop=0.2 --attr_drop=0.6
python main.py  --feat_drop=0.2 --attr_drop=0.5
python main.py  --feat_drop=0.2 --attr_drop=0.4
python main.py  --feat_drop=0.2 --attr_drop=0.3
python main.py  --feat_drop=0.2 --attr_drop=0.2
python main.py  --feat_drop=0.2 --attr_drop=0.1
python main.py  --feat_drop=0.2 --attr_drop=0
python main.py  --feat_drop=0.3 --attr_drop=0.6
python main.py  --feat_drop=0.3 --attr_drop=0.5
python main.py  --feat_drop=0.3 --attr_drop=0.4
python main.py  --feat_drop=0.3 --attr_drop=0.3
python main.py  --feat_drop=0.3 --attr_drop=0.2
python main.py  --feat_drop=0.3 --attr_drop=0.1
python main.py  --feat_drop=0.3 --attr_drop=0
python main.py  --feat_drop=0.4 --attr_drop=0.6
python main.py  --feat_drop=0.4 --attr_drop=0.5
python main.py  --feat_drop=0.4 --attr_drop=0.4
python main.py  --feat_drop=0.4 --attr_drop=0.3
python main.py  --feat_drop=0.4 --attr_drop=0.2
python main.py  --feat_drop=0.4 --attr_drop=0.1
python main.py  --feat_drop=0.4 --attr_drop=0
python main.py  --feat_drop=0.5 --attr_drop=0.6
python main.py  --feat_drop=0.5 --attr_drop=0.5
python main.py  --feat_drop=0.5 --attr_drop=0.4
python main.py  --feat_drop=0.5 --attr_drop=0.3
python main.py  --feat_drop=0.5 --attr_drop=0.2
python main.py  --feat_drop=0.5 --attr_drop=0.1
python main.py  --feat_drop=0.5 --attr_drop=0
python main.py  --feat_drop=0.6 --attr_drop=0.6
python main.py  --feat_drop=0.6 --attr_drop=0.5
python main.py  --feat_drop=0.6 --attr_drop=0.4
python main.py  --feat_drop=0.6 --attr_drop=0.3
python main.py  --feat_drop=0.6 --attr_drop=0.2
python main.py  --feat_drop=0.6 --attr_drop=0.1
python main.py  --feat_drop=0.6 --attr_drop=0